# Project Identification
sonar.projectKey=01e
sonar.projectName=01e_com
sonar.projectVersion=1.0
sonar.host.url=http://172.17.0.1:9000
sonar.modules=client,gateway_service,user_service,product_service,media_service
sonar.allowPropertiesWithNoFiles=true

# Exclude boilerplate classes from coverage calculations across all Java services
sonar.coverage.exclusions=**/*Application.java, **/config/**, **/entity/**, **/entities/**, **/dto/**, **/model/**

# Client (Angular Frontend) Configuration
client.sonar.projectName=Client
client.sonar.sources=src
client.sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**
client.sonar.tests=src
client.sonar.test.inclusions=**/*.spec.ts
client.sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Java Microservices Configurations
gateway_service.sonar.projectName=Gateway Service
gateway_service.sonar.sources=src/main/java
gateway_service.sonar.java.binaries=target/classes
gateway_service.sonar.junit.reportPaths=target/surefire-reports
gateway_service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

user_service.sonar.projectName=User Service
user_service.sonar.sources=src/main/java
user_service.sonar.java.binaries=target/classes
user_service.sonar.junit.reportPaths=target/surefire-reports
user_service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

product_service.sonar.projectName=Product Service
product_service.sonar.sources=src/main/java
product_service.sonar.java.binaries=target/classes
product_service.sonar.junit.reportPaths=target/surefire-reports
product_service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

media_service.sonar.projectName=Media Service
media_service.sonar.sources=src/main/java
media_service.sonar.java.binaries=target/classes
media_service.sonar.junit.reportPaths=target/surefire-reports
media_service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml